/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KatogumiRouteImport } from './routes/katogumi'
import { Route as IndexRouteImport } from './routes/index'

const KatogumiRoute = KatogumiRouteImport.update({
  id: '/katogumi',
  path: '/katogumi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/katogumi': typeof KatogumiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/katogumi': typeof KatogumiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/katogumi': typeof KatogumiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/katogumi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/katogumi'
  id: '__root__' | '/' | '/katogumi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KatogumiRoute: typeof KatogumiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/katogumi': {
      id: '/katogumi'
      path: '/katogumi'
      fullPath: '/katogumi'
      preLoaderRoute: typeof KatogumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KatogumiRoute: KatogumiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
